<div class="breadcrumbs-left">
    <div class="breadcrumbs-right">
        <div class="breadcrumbs-middle">
            <span>
                <?php
                echo $this->breadcrumbs;
                ?>
            </span>
        </div>
    </div>
</div>


<div class="driver-information form" id="main">
    <div class="post-top">
        <div class="post-bottom">
            <div class="post-middle">
                <div style="padding: 30px;">
                    <table class="inform">
                        <tbody>
                            <tr class="color-dark">
                                <td colspan="2">
                                    <h3>
                                        Your request has NOT YET been submitted. .. Please review and confirm the following information:
                                    </h3>
                                </td>
                            </tr>
                            <?php foreach ($this->equipmentInformationFields as $key => $value) : ?>
                            <tr><td style="color: red;"><?= "$key : $value"; ?></td> </tr>
                            <?php endforeach; ?>
                            <tr class="color-dark">
                                <td width="400">
                                    <h3>Error Checking: No Errors Found</h3>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="blue-nav" style="width:540px;">
                        <ul>
                            <li>
                                <span>
                                    <a href="/equipment/information-worksheet/show-complete-form/id/<?= $this->ID; ?>">
                                        Finalize Submission
                                    </a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="/equipment/information-worksheet/index/EIN/<?= $this->EIN; ?>">
                                        Cancel and Discard Application
                                    </a>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>