<div id="add-inspector-form" title="Create New Inspector">
    <form>
    <fieldset>
        <label for="in_first_name">First Name</label>
        <input type="text" name="in_first_name" id="in_first_name" class="text ui-widget-content ui-corner-all" /><br><br>
        <label for="in_last_name">Last Name</label>
        <input type="text" name="in_last_name" id="in_last_name" value="" class="text ui-widget-content ui-corner-all" /><br><br>
        <label for="in_certificate">Certificate</label>
        <input type="file" id="uploadCertificate" name="uploadCertificate" onChange="ajaxCertificateUpload();"/>
        <input type="hidden" id="in_certificate" name="in_certificate" /><br><br>
        <label for="in_service_provider_id">Service Provider</label>
        <select id="in_service_provider_id" class="spSelect">
            <?php
                foreach ($this->layout()->spList as $key => $value) {
                    echo '<option value="' . $key . '">' . $value . '</option>';
                }
            ?>
        </select><br><br>
    </fieldset>
    </form>
</div>