<table cellspacing="0" class="inform status-ok" style="float: none; width: 889px;" >
    <tbody>
    <tr>
        <th>
            <h2><?= $this->layout()->header; ?></h2>
        </th>
        <th>
            &nbsp;
        </th>
    </tr>
    </tbody>
</table>
<table cellspacing="0" class="inform" style="float: none; width: 889px;" >

<?php
$inspectionList = $this->layout()->inspectionList;
$inspectionCount = 0;
foreach($inspectionList as $key => $value)
{
    $inspectionCount++;
    ?>
    <tbody id="viewInspectionRecordID_<?= $value['ins_id']; ?>" class="classInspectionRecordID_<?= $value['ins_id']; ?>">
        <tr class="title-dark">
            <td colspan="2">
                Inspection #<?= $inspectionCount;?>
            <?php if ($this->layout()->identity->permissions->equipment_inspection_modify_permission === true) : ?>
                [ <a onclick="$('.classInspectionRecordID_<?= $value['ins_id']; ?>').toggle('slow');">EDIT</a> ]
            <?php endif; ?>
            <?php if ($this->layout()->identity->permissions->equipment_inspection_delete_permission === true) : ?>
                [ <a onclick="deleteInspectionClickHandler(<?= "{$value['ins_id']}, {$value['ins_equipment_id']}";?>)">DELETE</a> ]
            <?php endif; ?>
            </td>
        </tr>
        <tr  class="color-dark">
            <td colspan="2">
                Start Date:&nbsp;&nbsp;<span id="view_ins_start_date_<?= $value['ins_id']; ?>"><?= $value['ins_start_date']?></span>
                Start Time:&nbsp;&nbsp;<span id="view_ins_start_time_<?= $value['ins_id']; ?>"><?= $value['ins_start_time']?></span>

            </td>
        </tr>
        <tr>
            <td colspan="2">
                Next Date:&nbsp;&nbsp;<span id="view_ins_next_date_<?= $value['ins_id']; ?>"><?= $value['ins_next_date']?></span>
                Reinspection Date:&nbsp;&nbsp;<span id="view_ins_reinspection_date_<?= $value['ins_id']; ?>"><?= $value['ins_reinspection_date']?></span>
            </td>
        </tr>
        <tr  class="color-dark">
            <td colspan="2">
                Type:&nbsp;&nbsp;<span id="view_ins_type_id_<?= $value['ins_id']; ?>"><?= $value['it_type']?></span>
                Inspector:&nbsp;&nbsp;<span id="view_ins_inspector_id_<?= $value['ins_id']; ?>"><?= $value['in_first_name'] . ' ' . $value['in_last_name']?></span>
                Result:&nbsp;&nbsp;<span id="view_ins_result_id_<?= $value['ins_id']; ?>"><?= $value['ir_result']?></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                DOT regulated:&nbsp;&nbsp;<span id="view_ins_dot_regulated_<?= $value['ins_id']; ?>"><?= $value['ins_dot_regulated']?></span>
                Diesel information:&nbsp;&nbsp;<span id="view_ins_diesel_inspection_information_<?= $value['ins_id']; ?>"><?= $value['ins_diesel_inspection_information']?></span>
            </td>
        </tr>
    </tbody>

    <tbody id="editInspectionRecordID_<?php echo $value['ins_id']; ?>" class="classInspectionRecordID_<?= $value['ins_id']; ?>" style="display: none;">
        <tr class="title-dark">
            <td colspan="2">
                Edit Inspection #<?= $inspectionCount;?> [ <a class="InspectionAddLinkClass" onclick="$('.classInspectionRecordID_<?= $value['ins_id']; ?>').toggle('slow');">HIDE</a> ]
            </td>
        </tr>
        <tr  class="color-dark">
            <td width="150">
                <label class="required">
                    <span>*</span>Start Date:
                </label>
            </td>
            <td>
                <input type="text" class="inspectionDate" id="ins_start_date_<?= $value['ins_id']; ?>"
                       size=12 value="<?= $value['ins_start_date']; ?>"/>&nbsp;&nbsp;&nbsp;
                <label class="required">
                    <span>*</span>Start Time:
                </label>
                <input type="text" id="ins_start_time_<?= $value['ins_id']; ?>"
                       size=12 value="<?= $value['ins_start_time']; ?>"/>
            </td>
        </tr>
        <tr>
            <td width="150">
                <label class="required">
                    <span>*</span>Next Date:
                </label>
            </td>
            <td>
                <input type="text" class="inspectionDate" id="ins_next_date_<?= $value['ins_id']; ?>"
                       size=12 value="<?= $value['ins_next_date']; ?>"/>&nbsp;&nbsp;&nbsp;
                <label>
                    Reinspection Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </label>
                <input type="text" class="inspectionDate" id="ins_reinspection_date_<?= $value['ins_id']; ?>"
                       size=12 value="<?= $value['ins_reinspection_date']; ?>"/>
            </td>
        </tr>
        <tr  class="color-dark">
            <td width="150">
                <label class="required">
                    <span>*</span>Type:
                </label>
            </td>
            <td>
                <select id="ins_type_id_<?= $value['ins_id']; ?>" >
                    <?php
                        foreach ($this->layout()->inspectionTypeList as $type_ind => $type_name) {
                            $selected = '';
                            if ($type_ind == $value['ins_type_id']) {
                                $selected = 'selected="selected"';
                            }
                          echo '<option value="' . $type_ind . '" ' . $selected . '>' . $type_name . '</option>';
                        }
                    ?>
                </select>
                &nbsp;&nbsp;&nbsp;
                <label class="required">
                    <span>*</span>Inspector:
                </label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <select id="ins_inspector_id_<?= $value['ins_id']; ?>"  class="inspectorSelect">
                    <?php
                        foreach ($this->layout()->inspectorList as $inspector_ind => $inspector_name) {
                            $selected = '';
                            if ($inspector_ind == $value['ins_inspector_id']) {
                                $selected = 'selected="selected"';
                            }
                          echo '<option value="' . $inspector_ind . '" ' . $selected . '>' . $inspector_name . '</option>';
                        }
                    ?>
                </select>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php if ($this->layout()->identity->permissions->inspector_create_permission === true) : ?>
                    <a onclick="createInspectorClickHeandler();">New Inspector</a>
                <?php endif; ?>
                &nbsp;&nbsp;&nbsp;
                <label class="required">
                    <span>*</span>Result:
                </label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <select id="ins_result_id_<?= $value['ins_id']; ?>" >
                    <?php
                        foreach ($this->layout()->inspectionResultList as $result_ind => $result_name) {
                            $selected = '';
                            if ($result_ind == $value['ins_result_id']) {
                                $selected = 'selected="selected"';
                            }
                          echo '<option value="' . $result_ind . '" ' . $selected . '>' . $result_name . '</option>';
                        }
                    ?>
                </select>&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
        </tr>
        <tr>
            <td width="150">
                <label class="required">
                    <span>*</span>DOT regulated:
                </label>
            </td>
            <td>
                <?php
                    $yesChecked = '';
                    $noChecked = '';
                    if (isset($value['ins_dot_regulated']) && $value['ins_dot_regulated'] == 'No') {
                        $noChecked = 'checked="checked"';
                    } else if (isset($value['ins_dot_regulated']) && $value['ins_dot_regulated'] == 'Yes') {
                        $yesChecked = 'checked="checked"';
                    }
                ?>
                <input type="radio" class="ins_dot_regulated_<?= $value['ins_id']; ?>"
                       name="ins_dot_regulated_<?= $value['ins_id']; ?>" id="ins_dot_regulated_yes"
                       value="Yes" <?= $yesChecked; ?>>&nbsp;Yes
                <input type="radio" class="ins_dot_regulated_<?= $value['ins_id']; ?>"
                       name="ins_dot_regulated_<?= $value['ins_id']; ?>" id="ins_dot_regulated_no"
                       value="No" <?= $noChecked; ?>>&nbsp;No
                &nbsp;&nbsp;&nbsp;
                <label>
                    Diesel information:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </label>
                <input type="text" id="ins_diesel_inspection_information_<?= $value['ins_id']; ?>"
                       size=12 value="<?= $value['ins_diesel_inspection_information']; ?>"/>
                
            </td>
        </tr>
        <tr height=40 valign=middle>
            <td class="" align=center>&nbsp;</td>
            <td class="" align=left>
                <span class="blue-button float-left">
                    <a id="saveInspection"  class="saveBlockButtonClass" onclick="saveInspection(<?= $value['ins_id'] . ',' . $value['ins_equipment_id'];?>);">
                        Save
                    </a>
                </span>
            </td>
        </tr>
    </tbody>

    <?php
        }
?>

</table>
<?= $this->partial('partials/index/_add-inspection-equipment.phtml',array(
                                'inspectionTypeList' => $this->layout()->inspectionTypeList,
                                'inspectionResultList' => $this->layout()->inspectionResultList,
                                'inspectorList' => $this->layout()->inspectorList,
                                'identity' => $this->layout()->identity
                        )
                );
?>